services:
  backend:
    build: ./backend
    container_name: goscript-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/src/interpreter/grammar:/app/dist/interpreter/grammar

  frontend:
    build: ./frontend
    container_name: goscript-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend