# ============================
# Etapa 1: Build
# ============================
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# ============================
# Etapa 2: Producción
# ============================
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./

# Copiar la gramática Jison al dist
COPY src/interpreter/grammar ./dist/interpreter/grammar

EXPOSE 3000

CMD ["node", "dist/main"]